name: Release Alfred Workflow

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          chmod +x ./build.zsh
          ./build.zsh

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.alfredworkflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


